# Generated by Django 2.1.1 on 2019-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('article', models.ManyToManyField(related_name='tag', to='articles.Article')),
            ],
            options={
                'verbose_name': 'Разделы',
            },
        ),
    ]
