# Generated by Django 2.1.1 on 2019-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='tag', to='articles.Article'),
        ),
    ]
