# Generated by Django 2.1.5 on 2019-06-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190615_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
