# Generated by Django 2.1.5 on 2019-06-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190616_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='main',
        ),
    ]
