# Generated by Django 2.1.5 on 2019-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_section_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
