# Generated by Django 2.1.5 on 2019-06-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_section_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='articles.Section'),
        ),
    ]
