# Generated by Django 2.1.5 on 2019-06-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190616_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='section',
            name='main',
        ),
        migrations.AddField(
            model_name='section',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='tag', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
