# Generated by Django 2.1.5 on 2019-06-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='tag', to='articles.Section'),
        ),
    ]
