# Generated by Django 2.1.5 on 2019-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20190616_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='section',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='tag', to='articles.Article'),
        ),
    ]
