# Generated by Django 2.1.5 on 2019-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20190617_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Tags', to='articles.Section'),
        ),
    ]
