# Generated by Django 2.1.1 on 2019-06-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20190617_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.Article'),
        ),
    ]
